djangoprojects/blogproject/accounts/urls.py
from django.conf.urls import url
from accounts import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
]

urlpatterns += staticfiles_urlpatterns()

djangoprojects/blogproject/blogproject/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from blogproject import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^posts/', include('posts.urls')),
    url(r'^publish/', views.publish),
    url(r'^users/', include('users.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^select/', views.select, name='select'),
    url(r'^$', views.home, name='home'),
]

urlpatterns += staticfiles_urlpatterns()

djangoprojects/blogproject/posts/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'posts'

urlpatterns = [
    url(r'^$', views.topic_list, name='topic_list'),
    url(r'^publish/$', views.publish, name='publish'),
    url(r'^(?P<topic>[\w|\W]+)/(?P<title>[\w|\W]+)/(?P<user>[\w|\W]+)/$', views.topic_title_user_detail, name='topic_title_user_detail'),
    url(r'^(?P<topic>[\w|\W]+)/(?P<title>[\w|\W]+)/$', views.topic_title_detail, name='topic_title_detail'),
    url(r'^(?P<topic>[\w|\W]+)/$', views.single_topic_list, name='single_topic_list'),
]

djangoprojects/blogproject/users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^$', views.user_list, name='user_list'),
    url(r'^(?P<username>[\w|\W]+)/(?P<topic>[\w|\W]+)/(?P<title>[\w|\W]+)/$', views.user_topic_title_detail, name='user_topic_title_detail'),
    url(r'^(?P<username>[\w|\W]+)/(?P<topic>[\w|\W]+)/$', views.user_topic_detail, name='user_topic_detail'),
    url(r'^(?P<username>[\w|\W]+)/$', views.single_user_posts, name='single_user_posts'),
]

djangoprojects/blogproject/accounts/models.py
from django.db import models

# Create your models here.

djangoprojects/blogproject/posts/models.py
from django.db import models

# Create your models here.

class BlogTopic(models.Model):
    title = models.CharField(max_length=35)
    created = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.title


class BlogUser(models.Model):
    username = models.CharField(max_length=30, unique = True)
    password = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.username


class BlogPost(models.Model):
    title = models.CharField(max_length=36)
    message = models.TextField(max_length=250)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(null=True)
    topic = models.ForeignKey(BlogTopic, on_delete=models.CASCADE)
    user = models.ForeignKey(BlogUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

djangoprojects/blogproject/posts/forms.py
from django import forms
from posts.models import BlogPost

class BlogPostForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ('title', 'message', 'topic', 'user')

djangoprojects/blogproject/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/select/')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
       form = AuthenticationForm(data=request.POST)
       if form.is_valid():
           user = form.get_user()
           login(request, user)
           return redirect('/select/')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

djangoprojects/blogproject/blogproject/views.py
import django.http
from django.shortcuts import render

def home(request):
    return render(request,'index.html')

def publish(request):
    return render(request, 'publish.html')

def select(request):
    return render(request, 'home.html')

djangoprojects/blogproject/posts/views.py
from django.shortcuts import render, redirect
from .models import BlogPost
from .models import BlogTopic
from .models import BlogUser
from .forms import BlogPostForm
from django.db.models import Count
from django.contrib.auth.decorators import login_required

@login_required(login_url="/accounts/login/")
def topic_list(request):
    all_topics = BlogTopic.objects.filter(pk__in=BlogPost.objects.values('topic').annotate(count=Count('topic')).values('topic')).annotate(tcount=Count('title')).values('title')
    return render(request, 'posts/topics.html', {'listoftopics':all_topics})

@login_required(login_url="/accounts/login/")
def single_topic_list(request, topic):
    single_topic_list = BlogPost.objects.filter(topic = BlogTopic.objects.get(title=topic)).annotate(tcount=Count('title')).values('topic','title').annotate(count=Count('topic')).values('topic','title')
    return render(request, 'posts/blogtopictitle.html', {'singletopiclist':single_topic_list, 'tpc':topic})

@login_required(login_url="/accounts/login/")
def topic_title_detail(request, topic, title):
    t = BlogTopic.objects.get(title=topic)
    topic_detail = BlogPost.objects.filter(topic = t, title=title)
    return render(request, 'posts/blogpost.html', {'topicdetail':topic_detail})

@login_required(login_url="/accounts/login/")
def topic_title_user_detail(request, topic, title, user):
    u = BlogUser.objects.get(username=user)
    t = BlogTopic.objects.get(title__contains=topic)
    topic_detail = BlogPost.objects.filter(topic = t, title=title, user=u)
    return render(request, 'posts/blogpost.html', {'topicdetail':topic_detail})

@login_required(login_url="/accounts/login/")
def publish(request):
    if request.method == "POST":
        form = BlogPostForm(request.POST)
        if form.is_valid():
            user = form.cleaned_data['user']
            title = form.cleaned_data['title']
            message = form.cleaned_data['message']
            topic = form.cleaned_data['topic']
            t = BlogTopic.objects.filter(title=topic)[0]
            u = BlogUser.objects.filter(username=user)[0]
            p = BlogPost(user=u, topic=t, title=title, message=message)
            p.save()
            return redirect('select')
    else:
        form = BlogPostForm()
    return render(request, 'posts/publish.html', {'form': form})

djangoprojects/blogproject/users/views.py
from django.shortcuts import render
from posts.models import BlogPost
from posts.models import BlogTopic
from posts.models import BlogUser
from django.db.models import Count


def user_list(request):
    all_users = BlogUser.objects.all()
    print("burda0")
    print(all_users)
    return render(request, 'users/users.html', {'listofusers':all_users})

def single_user_posts(request, username):
    print("burda1")
    u = BlogUser.objects.get(username=username)
    tlist = BlogPost.objects.filter(user=u).annotate(tcount=Count('topic')).values('topic')
    single_user_list = BlogPost.objects.filter(user = u, topic__in=tlist).values('topic','user').annotate(tcount=Count('topic'))
    single_usertopic_list = BlogTopic.objects.filter(pk__in=tlist).values('title')
    return render(request, 'users/blogusertitle.html', {'singleuserlist':single_usertopic_list, 'usr':username})

def user_topic_detail(request, username, topic):
    print("burda2")
    print(username)
    print(topic)
    t = BlogTopic.objects.filter(title=topic)
    u = BlogUser.objects.get(username=username)
    blog_detail = BlogPost.objects.filter(topic__in=t, user = u)
    return render(request, 'users/blogpost.html', {'blogdetail':blog_detail})

def user_topic_title_detail(request, topic, title, user):
    print("burda3")
    u = BlogUser.objects.get(username=user)
    t = BlogTopic.objects.get(title=topic)
    blog_detail = BlogPost.objects.filter(topic = t, title=title, user=u)
    return render(request, 'users/blogpost.html', {'blogdetail':blog_detail})

djangoprojects/blogproject/accounts/templates/accounts/login.html
{% extends 'base_template.html' %}
{% block content %}
    <h1>Login</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
       <input type="submit" value="Login">
    </form>
{% endblock %}

djangoprojects/blogproject/accounts/templates/accounts/signup.html
{% extends 'base_template.html' %}
{% block content %}
    <h1>Singup</h1>
    <form class="site-form" action="/accounts/signup/" method="post">
        {% csrf_token %}
        {{ form }}
       <input type="submit" value="Signup">
    </form>
{% endblock %}

djangoprojects/blogproject/posts/templates/posts/blogpost.html
{% extends 'post_template.html' %}

{% block content %}

    <head>
        <title>List of Topic </title>
    </head>
    <body>
        <div class="posts">
            {% for item in topicdetail %}
            <div class="post">
                <h1>Topic: {{ item.topic }}</a></h1>
                <h2>Title: {{ item.title }}</h2>
                <p>Message: {{ item.message }}</p>
                <p>Created on: {{ item.created }}</p>
                <p>User: {{ item.user }}</p>
            </div>
            {% endfor %}
        </div>
    </body>

{% endblock %}

djangoprojects/blogproject/posts/templates/posts/blogtopictitle.html
{% extends 'post_template.html' %}
{% load static %}
{% block content %}

    <head>
        <title>List of Topic </title>
    </head>
    <body>
        <div class="posts">
            {% for item in singletopiclist %}
            <div class="post">
                <h2><a href="{% url 'posts:topic_title_detail' topic=tpc title=item.title %}">
                    <img src="{% static '/img/common/arrow.png' %}"width="2%" height="5%" />{{ item.title }}</a></h2>
            </div>
            {% endfor %}
        </div>
    </body>

{% endblock %}

djangoprojects/blogproject/posts/templates/posts/publish.html
{% extends 'post_template.html' %}
{% block content %}
    <div class="publish-post">
        <h2>Publish</h2>
        <div class="publish">
            <form method="POST" class="post-form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="save btn btn-default">Save</button>
            </form>
        </div>
    </div>
{% endblock %}

djangoprojects/blogproject/posts/templates/posts/topics.html
{% extends 'post_template.html' %}
{% load static %}
{% block content %}

    <head>
        <title>List of Topics</title>
    </head>
    <body>
        <h1><img src="{% static '/img/common/topic.png' %}" width="10%" height="20%"/>By Topic</h1>
        <div class="posts">
            {% for item in listoftopics %}
            <div class="post">
                <a href="{% url 'posts:single_topic_list' topic=item.title %}">
                    <img src="{% static '/img/common/arrow.png' %}"width="2%" height="5%" />{{item.title}}</a>
            </div>
            {% endfor %}
        </div>
    </body>

{% endblock %}

djangoprojects/blogproject/templates/base_template.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="{% static '/css/layouts/blog.css' %}">
    </head>
    <body>
        <header class="wrapper">
            <h1>Welcome</h1>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

djangoprojects/blogproject/templates/home.html
{% load static %}
<html>
    <head>
        <title>Homepage Blog Exercise</title>
            <nav>
                <div class="other" align="right">
                <form class="logoutsite" action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <div class="alignment" align="right">
                        <button type="submit"><img src="{% static '/img/common/logout.png' %}" width="30px" length="30px"/></button>
                    </div>
                </form>
                </div>

            </nav>
    </head>
    <body>
        <center><h1>Please select ... </h1></center>
        <center><table style="width:50%">
            <tr>
                <td><h2><center><a href="{% url 'posts:topic_list' %}"><img src="{% static '/img/common/topic.png' %}" width="200px" length="200px" title="search by topic"/></a></center></h2></td>
                <td><h2><center><a href="{% url 'users:user_list' %}"><img src="{% static '/img/common/user-group.png' %}" width="200px" length="200px" title="search by user"/></a></center></h2></td>
                <td><h2><center><a href="{% url 'posts:publish' %}"><img src="{% static '/img/common/publish.png' %}" width="200px" length="200px" title="publish new post"/></a></center></h2></td>
            </tr>
        </table></center>
    </body>
</html>

djangoprojects/blogproject/templates/index.html
{% load static %}
<html>
    <head>
        <title>Homepage Blog Exercise</title>
    </head>
    <body>
        <h1>Welcome to my blog</h1>
        <center><h1>Please select ... </h1></center>
        <center><table style="width:50%">
            <tr>
                <td><h2><center><a href="{% url 'accounts:signup' %}"><img src="{% static '/img/common/signup-icon.png' %}" width="200px" length="200px" title="signup"/></a></center></h2></td>
                <td><h2><center><a href="{% url 'accounts:login' %}"><img src="{% static '/img/common/login.svg' %}" width="200px" length="200px" title="login"/></a></center></h2></td>
            </tr>
        </table></center>
    </body>
</html>

djangoprojects/blogproject/templates/post_template.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="{% static '/css/layouts/blog.css' %}">
            <nav>
                <form class="logoutsite" action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <div class="alignment" align="right">
                        <button type="submit"><img src="{% static '/img/common/logout.png' %}" width="30px" length="30px"/></button>
                    </div>
                </form>
            </nav>
    </head>
    <body>
        <div class="tmplt">
            <h1><a href="{% url 'posts:topic_list' %}"></a></h1>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

djangoprojects/blogproject/templates/user_template.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="{% static '/css/layouts/blog.css' %}">
            <nav>
                <form class="logoutsite" action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <div class="alignment" align="right">
                        <button type="submit"><img src="{% static '/img/common/logout.png' %}" width="30px" length="30px"/></button>
                    </div>
                </form>
            </nav>
    </head>
    <body>
        <div class="tmplt">
            <h1><a href="{% url 'users:user_list' %}"></a></h1>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

djangoprojects/blogproject/users/templates/users/blogpost.html
{% extends 'user_template.html' %}

{% block content %}

    <head>
        <title>List of Topic </title>
    </head>
    <body>
        <div class="users">
            {% for item in blogdetail %}
            <div class="user">
                <h2>Topic: {{ item.topic }}</a></h2>
                <p>Title: {{ item.title }}</p>
                <p>Message: {{ item.message }}</p>
                <p>Created on: {{ item.created }}</p>
                <p>User: {{ item.user }}</p>
            </div>
            {% endfor %}
        </div>
    </body>

{% endblock %}

djangoprojects/blogproject/users/templates/users/blogusertitle.html
{% extends 'user_template.html' %}
{% load static %}
{% block content %}

    <head>
        <title>List of Topic </title>
    </head>
    <body>
        <div class="users">
            {% for item in singleuserlist %}
            <div class="user">
                <h2><a href="{% url 'users:user_topic_detail' topic=item.title username=usr %}">
                    <img src="{% static '/img/common/arrow.png' %}"width="2%" height="5%" />{{ item.title }}</a></h2>
            </div>
            {% endfor %}
        </div>
    </body>

{% endblock %}

djangoprojects/blogproject/users/templates/users/users.html
{% extends 'user_template.html' %}
{% load static %}
{% block content %}

    <head>
        <title>List of Users</title>
    </head>
    <body>
        <h1><img src="{% static '/img/common/user-group.png' %}" width="10%" height="20%"/>By User</h1>
        <div class="users">
            {% for item in listofusers %}
                <div class="user">
                    <a href="{% url 'users:single_user_posts' username=item.username %}">
                        <img src="{% static '/img/common/arrow.png' %}"width="2%" height="5%" />{{item.username}}</a>
                </div>
            {% endfor %}
        </div>
    </body>

{% endblock %}